---
- name: Converge
  hosts: all
  become: yes
  pre_tasks:
    - add_host:
        name: delegated-travis-instance
        ansible_python_interpreter: '/home/travis/virtualenv/python2.7/bin/python'
      changed_when: False

    - add_host:
        name: testboot.lxc
        groups: testboot
        lxc_container_config:
        - "lxc.mount.entry={{ playbook_dir }} srv none defaults,bind,create=dir,uid=0 0 0"
      changed_when: False
  roles:
    - role: ansible-boot-lxc
